# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "Marathon19"
repo_name: "arxiv-papers-daily"
show_authors: True
show_links: True
show_badge: True
max_results: 10

publish_readme: True
publish_gitpage: True
publish_wechat: False

# file paths
json_readme_path: './docs/cv-arxiv-daily.json'
json_gitpage_path: './docs/cv-arxiv-daily-web.json'
json_wechat_path: './docs/cv-arxiv-daily-wechat.json'

md_readme_path: 'README.md'
md_gitpage_path: './docs/index.md'
md_wechat_path: './docs/wechat.md'

# keywords to search
keywords:
    "Tropical Cyclone": 
        # filters: ["Tropical Cyclone Forecast","Tropical Cyclone Forecasting",
        # "Tropical Cyclone Predict","Tropical Cyclone Prediction",
        # "Tropical Cyclone Trajectory Forecast","Tropical Cyclone Trajectories Forecast",
        # "Tropical Cyclone Trajectory Predict","Tropical Cyclone Trajectories Prediction",
        # "Tropical Cyclone Intensity Forecast","Tropical Cyclone Intensity Forecast",
        # "Tropical Cyclone Intensity Predict","Tropical Cyclone Intensity Prediction"]
        filters: ["Tropical Cyclone"]
    "Typhoon":
        # filters: ["Typhoon Forecast","Typhoon Forecasting",
        # "Typhoon Predict","Typhoon Prediction",
        # "Typhoon Trajectory Forecast","Typhoon Trajectories Forecast",
        # "Typhoon Trajectory Predict","Typhoon Trajectories Prediction",
        # "Typhoon Intensity Forecast","Typhoon Intensity Forecast",
        # "Typhoon Intensity Predict","Typhoon Intensity Prediction"]
        filters: ["Typhoon"]
    "Estimation":
        filters: ["Tropical Cyclone Estimation","Typhoon Estimation",
        "Tropical Cyclone Intensity Estimation","Typhoon Intensity Estimation"]
